https://leetcode.com/problems/integer-to-english-words/description/
https://leetcode.com/problems/basic-calculator-iii/submissions/1193201825/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/problems/find-the-duplicate-number/description/
https://leetcode.com/problems/binary-tree-longest-consecutive-sequence-ii/description/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/problems/kth-largest-sum-in-a-binary-tree/
https://leetcode.com/problems/find-permutation/editorial/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/problems/maximum-average-subarray-ii/description/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/problems/factor-combinations/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/problems/find-root-of-n-ary-tree/description/?envType=study-plan-v2&envId=premium-algo-100
https://leetcode.com/tag/design
https://leetcode.com/problems/lru-cache/
